### ISSUE TITLE
Welcome function needs update

### ISSUE THREAD

**Issue by Philbilly** [tanaaKa/Coalition-Mission-Framework-Mod#24]
Will need new medical role descriptions for the welcome script. 

Im sure someone could come up with more elegant ones than I can. 

Link for reference:

https://github.com/tanaaka/Coalition-Mission-Framework-Mod/blob/main/addons/framework/misc/welcome/fn_initWelcome.sqf

**Comment by tanaaKa** [comment]
Updated in https://github.com/tanaaKa/Coalition-Mission-Framework-Mod/pull/23
